version: '3'
services:
    consul:
      image: progrium/consul:latest
      restart: always
      hostname: consul-master
      ports:
        - "8400:8400"
        - "8500:8500"
        - "8600:53/udp"
      command: "-server -bootstrap -ui-dir /ui"
    registrator:
      image: gliderlabs/registrator:latest
      restart: always
      hostname: registrator-master
      volumes:
        - "/var/run/docker.sock:/tmp/docker.sock"
      command: "-ip ${CURRENT_IP} consul://${CURRENT_IP}:8500"
    elb:
      build:
        context: ../nginx-consul-template
        args:
          SERVICE: web
      restart: always
      hostname: elb-master
      environment:
        CONSUL: "${CURRENT_IP}:8500"
      ports:
        - "9080:80"
    web:
      image: nginx:latest
      restart: always
      hostname: nginx
      ports:
        - "80"
      environment:
        SERVICE_NAME: web
